### ISSUE TITLE
Fix broken link to DOT Code of Federal Regulations [CFR] 49

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/nitrate-policy#7]
The link to [(DOT Code of Federal Regulations [CFR] 49)](https://hazmatonline.phmsa.dot.gov/services/publication_documents/howtouse0507.pdf) in the [Nitrate Policy](https://docs.rockarch.org/nitrate-policy) leads to a page that is no longer available online. 

@rogercasement1916 , is there a link to a different page that could replace this one?

**Comment by rogercasement1916** [comment]
The following link can replace current broken link in Nitrate policy doc:

https://www.ecfr.gov/current/title-49

-Brent

_________________________

Audiovisual Archivist

He/Him

Rockefeller Archive Center

15 Dayton Avenue

Sleepy Hollow, NY 10591

914-366-6324

"Ní neart go cur le chéile"

________________________________
From: Hannah Sistrunk ***@***.***>
Sent: Thursday, January 11, 2024 11:29 AM
To: RockefellerArchiveCenter/nitrate-policy ***@***.***>
Cc: Phillips, Brent ***@***.***>; Mention ***@***.***>
Subject: [RockefellerArchiveCenter/nitrate-policy] Fix broken link to DOT Code of Federal Regulations [CFR] 49 (Issue #7)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
EXTERNAL WARNING: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



The link to (DOT Code of Federal Regulations [CFR] 49)<https://urldefense.proofpoint.com/v2/url?u=https-3A__hazmatonline.phmsa.dot.gov_services_publication-5Fdocuments_howtouse0507.pdf&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=a-QLPcEyXA9SPq53811fiLbjKwtPPh-Kq3fBIxsIR7w&m=nVHtEWBr5P6PNOoD5_xOuE8fKjR331mCYHdpPxt7ZbFPJwk6yiHwOU4dFgJZX0Ac&s=SF4HmAVppH764CGc55iSDUCoHQrQjye5M9lQYybGhgc&e=> leads to a page that is no longer available online.

@rogercasement1916<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rogercasement1916&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=a-QLPcEyXA9SPq53811fiLbjKwtPPh-Kq3fBIxsIR7w&m=nVHtEWBr5P6PNOoD5_xOuE8fKjR331mCYHdpPxt7ZbFPJwk6yiHwOU4dFgJZX0Ac&s=x8LIKCAtZlnojntjARya_Ha2LCaDpHpzEHhzDAo1LTk&e=> , is there a link to a different page that could replace this one?
